/*
 * MIT License
 *
 * Copyright (c) 2020 David Greven
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * This file was auto-generated by FATE (Fully Automatically Transcribes Entities)
 * --------------------------------------------------
 * 	FATE version:	0.1.8-2
 * 	Timestamp:		2020-05-09 23:43:44.062741
 * 	SQL's MD5:		76547e739d7d88a3b9e8c6e6e42ce89f
 * --------------------------------------------------
 * 	Human reviewers:	None
 * 	Modified by human:	False
 */

package entities;

import grevend.persistencelite.entity.Entity;
import grevend.persistencelite.entity.Id;
import grevend.persistencelite.entity.Property;

@Entity(name = "country")
public record Country (

    @Id(autoGenerated = true)
    int id,

    @Property(name = "name")
    String name,

    @Property(name = "code")
    String code

) {}
